[build]
  publish = "."

[[redirects]]
  from = "/styles.css"
  to = "/styles.css"
  status = 200

[[redirects]]
  from = "/app.js"
  to = "/app.js"
  status = 200

[[redirects]]
  from = "/login.html"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200

[[redirects]]
  from = "/downloads/*"
  to = "/downloads/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
