"""
PlaySpec Gaming IQ & Trivia Comprehensive Question Database
Contains 150+ structured questions:
- 50 Easy Questions (Rookie, 100 pts)
- 50 Medium Questions (Veteran, 200 pts)
- 50 Hard Questions (Hardcore / Elden God, 350-500 pts)
Spanning: RPG Lore, PC Hardware, Esports & FPS, Retro & Indie, and Industry Trivia.
"""

EASY_QUESTIONS = [
    # RPG & AAA Lore (Easy)
    {"id": "e_rpg_1", "category": "rpg_lore", "category_label": "🗡️ RPG & AAA Lore", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "In 'The Witcher 3: Wild Hunt', what is the name of Geralt of Rivia's horse?",
     "options": ["Roach", "Shadowmere", "Agro", "Epona"], "correct": "Roach",
     "lore_fact": "Geralt names every horse he ever owns 'Roach' (Płotka in Polish)."},
    {"id": "e_rpg_2", "category": "rpg_lore", "category_label": "🗡️ RPG & AAA Lore", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "In 'Skyrim', what iconic 3-word dragon shout translates to 'Force, Balance, Push'?",
     "options": ["Fus Ro Dah", "Yol Toor Shul", "Wuld Nah Kest", "Lok Vah Koor"], "correct": "Fus Ro Dah",
     "lore_fact": "Fus Ro Dah is the Unrelenting Force shout taught by the Greybeards at High Hrothgar."},
    {"id": "e_rpg_3", "category": "rpg_lore", "category_label": "🗡️ RPG & AAA Lore", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "In 'Cyberpunk 2077', what is the name of the main neon-drenched metropolis setting?",
     "options": ["Night City", "Neo Tokyo", "Raccoon City", "Los Santos"], "correct": "Night City",
     "lore_fact": "Night City was originally founded by developer Richard Night in 1994 as Coronado City."},
    {"id": "e_rpg_4", "category": "rpg_lore", "category_label": "🗡️ RPG & AAA Lore", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "In 'Grand Theft Auto V', which of the following is NOT one of the three playable protagonists?",
     "options": ["Niko Bellic", "Michael De Santa", "Franklin Clinton", "Trevor Philips"], "correct": "Niko Bellic",
     "lore_fact": "Niko Bellic was the main protagonist of Grand Theft Auto IV in Liberty City."},
    {"id": "e_rpg_5", "category": "rpg_lore", "category_label": "🗡️ RPG & AAA Lore", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "Who is the legendary protagonist of the 'God of War' series?",
     "options": ["Kratos", "Zeus", "Ares", "Atreus"], "correct": "Kratos",
     "lore_fact": "Kratos is the Ghost of Sparta who eventually journeys into Norse mythology with his son Atreus."},
    {"id": "e_rpg_6", "category": "rpg_lore", "category_label": "🗡️ RPG & AAA Lore", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "In 'Fallout', what is the name of the iconic blue-and-yellow vault jumpsuit mascot?",
     "options": ["Vault Boy", "Pip-Boy", "Bobblehead", "Nuka-Cola Man"], "correct": "Vault Boy",
     "lore_fact": "Vault Boy illustrates the perks and stats throughout the Vault-Tec training manuals."},
    {"id": "e_rpg_7", "category": "rpg_lore", "category_label": "🗡️ RPG & AAA Lore", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "In 'Elden Ring', what is the name of your spectral spectral steed?",
     "options": ["Torrent", "Shadowmere", "Maliketh", "Leonard"], "correct": "Torrent",
     "lore_fact": "Torrent is summoned using the Spectral Steed Whistle given to you by Melina."},
    {"id": "e_rpg_8", "category": "rpg_lore", "category_label": "🗡️ RPG & AAA Lore", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "In 'Red Dead Redemption 2', which gang does Arthur Morgan belong to?",
     "options": ["Van der Linde Gang", "O'Driscoll Boys", "Del Lobo Gang", "Lemoyne Raiders"], "correct": "Van der Linde Gang",
     "lore_fact": "Dutch van der Linde led the outlaw gang across the changing American frontier."},
    {"id": "e_rpg_9", "category": "rpg_lore", "category_label": "🗡️ RPG & AAA Lore", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "In 'Dark Souls', what resting place replenishes your Estus Flasks and resets enemies?",
     "options": ["Bonfire", "Shrine", "Lantern", "Grace Site"], "correct": "Bonfire",
     "lore_fact": "Bonfires are lit with coiled swords and fueled by the bones of the Undead."},
    {"id": "e_rpg_10", "category": "rpg_lore", "category_label": "🗡️ RPG & AAA Lore", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "In 'Assassin\\'s Creed', what is the name of the iconic hidden weapon strapped to assassins' wrists?",
     "options": ["Hidden Blade", "Phantom Dagger", "Wrist Katana", "Shadow Needle"], "correct": "Hidden Blade",
     "lore_fact": "Early assassins had to sacrifice their ring finger to use the hidden blade properly."},

    # PC Hardware & Tech (Easy)
    {"id": "e_hw_1", "category": "hardware", "category_label": "🖥️ PC Hardware & Tech", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "What does 'GPU' stand for in gaming hardware?",
     "options": ["Graphics Processing Unit", "General Power Unit", "Gaming Performance Utility", "Global Pixel Unit"], "correct": "Graphics Processing Unit",
     "lore_fact": "The GPU handles 3D polygon rasterization, ray tracing, and shader computations."},
    {"id": "e_hw_2", "category": "hardware", "category_label": "🖥️ PC Hardware & Tech", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "What does 'FPS' stand for when measuring gaming smoothness?",
     "options": ["Frames Per Second", "Fixed Pixel Shader", "Fast Performance Speed", "Frame Pixel Scale"], "correct": "Frames Per Second",
     "lore_fact": "60 FPS is the standard target for smooth gameplay, while esports gamers prefer 144+ FPS."},
    {"id": "e_hw_3", "category": "hardware", "category_label": "🖥️ PC Hardware & Tech", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "What does 'DLSS' stand for in NVIDIA RTX graphics cards?",
     "options": ["Deep Learning Super Sampling", "Direct Lighting Spatial Shading", "Dynamic Low Synchronous System", "Digital Light Source Simulation"], "correct": "Deep Learning Super Sampling",
     "lore_fact": "NVIDIA DLSS uses AI Tensor cores to render at lower res and upscale sharply."},
    {"id": "e_hw_4", "category": "hardware", "category_label": "🖥️ PC Hardware & Tech", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "Which storage drive type is dramatically faster than traditional spinning hard drives (HDDs)?",
     "options": ["SSD (Solid State Drive)", "Floppy Disk", "Optical DVD-ROM", "Magnetic Tape"], "correct": "SSD (Solid State Drive)",
     "lore_fact": "NVMe SSDs read data over 5,000+ MB/s compared to ~120 MB/s on older HDDs."},
    {"id": "e_hw_5", "category": "hardware", "category_label": "🖥️ PC Hardware & Tech", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "What is the primary function of RAM in a gaming PC?",
     "options": ["High-speed temporary working memory for active programs", "Long-term permanent file storage", "Rendering 3D polygon lighting", "Powering the cooling fans"], "correct": "High-speed temporary working memory for active programs",
     "lore_fact": "RAM allows the CPU to access active game assets nanoseconds faster than reading from disk."},
    {"id": "e_hw_6", "category": "hardware", "category_label": "🖥️ PC Hardware & Tech", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "What unit is monitor refresh rate measured in?",
     "options": ["Hertz (Hz)", "Gigahertz (GHz)", "Megapixels (MP)", "Teraflops (TFLOPS)"], "correct": "Hertz (Hz)",
     "lore_fact": "A 144Hz monitor refreshes the screen image 144 times every second."},
    {"id": "e_hw_7", "category": "hardware", "category_label": "🖥️ PC Hardware & Tech", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "What substance is applied between the CPU and cooler heatsink to facilitate heat transfer?",
     "options": ["Thermal Paste", "Cooling Glue", "Silicon Gel", "Liquid Nitrogen"], "correct": "Thermal Paste",
     "lore_fact": "Thermal paste fills microscopic air gaps on metal surfaces to conduct heat to the radiator."},
    {"id": "e_hw_8", "category": "hardware", "category_label": "🖥️ PC Hardware & Tech", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "What does 'RGB' stand for in gaming PC lighting and peripherals?",
     "options": ["Red, Green, Blue", "Resolution, Graphics, Boost", "Rate, Gain, Brightness", "Rasterized Gamma Buffer"], "correct": "Red, Green, Blue",
     "lore_fact": "By mixing Red, Green, and Blue light channels, RGB LEDs can produce 16.8 million colors."},
    {"id": "e_hw_9", "category": "hardware", "category_label": "🖥️ PC Hardware & Tech", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "What component supplies clean electrical power to all components in a PC build?",
     "options": ["PSU (Power Supply Unit)", "Motherboard", "UPS Battery", "Voltage Inverter"], "correct": "PSU (Power Supply Unit)",
     "lore_fact": "Quality PSUs convert wall AC power to steady 12V, 5V, and 3.3V DC rails."},
    {"id": "e_hw_10", "category": "hardware", "category_label": "🖥️ PC Hardware & Tech", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "What does '4K resolution' typically refer to in pixel width?",
     "options": ["3840 x 2160 pixels", "1920 x 1080 pixels", "2560 x 1440 pixels", "1280 x 720 pixels"], "correct": "3840 x 2160 pixels",
     "lore_fact": "4K UHD has exactly 4 times the pixel count of standard 1080p Full HD."},

    # FPS & Esports (Easy)
    {"id": "e_fps_1", "category": "esports", "category_label": "🎯 FPS & Esports", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "In 'Counter-Strike 2', what is the price of the iconic AWP sniper rifle?",
     "options": ["$4,750", "$3,100", "$5,000", "$4,200"], "correct": "$4,750",
     "lore_fact": "The AWP has remained priced at $4,750 across CS 1.6, Source, GO, and CS2."},
    {"id": "e_fps_2", "category": "esports", "category_label": "🎯 FPS & Esports", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "In 'VALORANT', which agent is the fiery British duelist capable of reviving himself with 'Run It Back'?",
     "options": ["Phoenix", "Brimstone", "Yoru", "Chamber"], "correct": "Phoenix",
     "lore_fact": "Phoenix hails from London and controls fire-based flashes and blaze walls."},
    {"id": "e_fps_3", "category": "esports", "category_label": "🎯 FPS & Esports", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "In 'Apex Legends', what flying dropship do players jump out of at the start of a match?",
     "options": ["The Dropship", "The Battle Bus", "The Pelican", "The Zeppelin"], "correct": "The Dropship",
     "lore_fact": "The jumpmaster chooses when the squad deploys toward designated high-tier loot zones."},
    {"id": "e_fps_4", "category": "esports", "category_label": "🎯 FPS & Esports", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "In 'Team Fortress 2', which class can disguise as enemy players and backstab for instant kills?",
     "options": ["Spy", "Scout", "Sniper", "Pyro"], "correct": "Spy",
     "lore_fact": "The Spy uses a Cloak-and-Dagger watch and an electronic sapper against Engineer sentries."},
    {"id": "e_fps_5", "category": "esports", "category_label": "🎯 FPS & Esports", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "In 'Overwatch 2', which gorilla scientist from the Horizon Lunar Colony wields a Tesla Cannon?",
     "options": ["Winston", "Hammond", "Reinhardt", "Doomfist"], "correct": "Winston",
     "lore_fact": "Winston loves peanut butter and invented Tracer's chronal accelerator."},
    {"id": "e_fps_6", "category": "esports", "category_label": "🎯 FPS & Esports", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "In 'Counter-Strike', what is the bomb called that Terrorists plant on sites A or B?",
     "options": ["C4 Explosive", "Semtex", "Claymore", "Dynamite"], "correct": "C4 Explosive",
     "lore_fact": "The standard C4 detonation timer is 40 seconds in official matchmaking."},
    {"id": "e_fps_7", "category": "esports", "category_label": "🎯 FPS & Esports", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "What popular Battle Royale title features building wooden walls, ramps, and the 'Battle Bus'?",
     "options": ["Fortnite", "PUBG", "Warzone", "H1Z1"], "correct": "Fortnite",
     "lore_fact": "Fortnite originally began as a co-op zombie tower defense game called 'Save the World'."},
    {"id": "e_fps_8", "category": "esports", "category_label": "🎯 FPS & Esports", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "In 'Call of Duty: Warzone', what is the 1v1 respawn arena where eliminated players fight for a second chance?",
     "options": ["The Gulag", "The Pit", "The Colosseum", "The Cage"], "correct": "The Gulag",
     "lore_fact": "Winning a 1v1 shootout in the Gulag grants immediate redeployment back onto Verdansk."},
    {"id": "e_fps_9", "category": "esports", "category_label": "🎯 FPS & Esports", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "What competitive tactical shooter developed by Riot Games features 5v5 bomb defusal with character abilities?",
     "options": ["VALORANT", "Rainbow Six Siege", "Overwatch", "Rogue Company"], "correct": "VALORANT",
     "lore_fact": "VALORANT launched in 2020 built on custom 128-tick rate servers."},
    {"id": "e_fps_10", "category": "esports", "category_label": "🎯 FPS & Esports", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "In 'Rainbow Six Siege', what are the two main opposing roles during a round?",
     "options": ["Attackers vs Defenders", "Terrorists vs Counter-Terrorists", "Survivors vs Hunters", "Mercenaries vs Police"], "correct": "Attackers vs Defenders",
     "lore_fact": "Defenders reinforce walls and set traps, while Attackers drone and breach destructible walls."},

    # Retro & Indie Legends (Easy)
    {"id": "e_indie_1", "category": "indie_retro", "category_label": "🕹️ Retro & Indie Legends", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "What is the famous Konami Code cheat sequence?",
     "options": ["Up, Up, Down, Down, Left, Right, Left, Right, B, A", "Up, Down, Up, Down, Left, Right, B, A", "Down, Down, Up, Up, Left, Right, A, B", "Left, Right, Left, Right, Up, Down, A, B"], "correct": "Up, Up, Down, Down, Left, Right, Left, Right, B, A",
     "lore_fact": "Created by Kazuhisa Hashimoto in 1986, the code gave players 30 lives in Contra."},
    {"id": "e_indie_2", "category": "indie_retro", "category_label": "🕹️ Retro & Indie Legends", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "In 'Minecraft', what green hiss-sound monster explodes when it gets near the player?",
     "options": ["Creeper", "Enderman", "Zombie", "Skeleton"], "correct": "Creeper",
     "lore_fact": "The Creeper was created by accident when Notch mixed up the height and length of a pig model."},
    {"id": "e_indie_3", "category": "indie_retro", "category_label": "🕹️ Retro & Indie Legends", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "In 'Portal', what is the name of the rogue AI that tests you with portal puzzles?",
     "options": ["GLaDOS", "Cortana", "SHODAN", "HAL 9000"], "correct": "GLaDOS",
     "lore_fact": "GLaDOS stands for Genetic Lifeform and Disk Operating System."},
    {"id": "e_indie_4", "category": "indie_retro", "category_label": "🕹️ Retro & Indie Legends", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "In 'Undertale', what skeleton brother tells bad puns and loves ketchup?",
     "options": ["Sans", "Papyrus", "Gaster", "Toriel"], "correct": "Sans",
     "lore_fact": "Sans's dialogue text is rendered in the Comic Sans font."},
    {"id": "e_indie_5", "category": "indie_retro", "category_label": "🕹️ Retro & Indie Legends", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "In 'Hollow Knight', what is your character's primary melee weapon called?",
     "options": ["Nail", "Sword", "Needle", "Blade"], "correct": "Nail",
     "lore_fact": "The Nailsmith in the City of Tears can forge and upgrade your Old Nail to a Pure Nail."},
    {"id": "e_indie_6", "category": "indie_retro", "category_label": "🕹️ Retro & Indie Legends", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "What 2011 sandbox game is often described as 2D Minecraft with deep boss battles?",
     "options": ["Terraria", "Starbound", "Stardew Valley", "Don't Starve"], "correct": "Terraria",
     "lore_fact": "Terraria has sold over 44 million copies worldwide developed by Re-Logic."},
    {"id": "e_indie_7", "category": "indie_retro", "category_label": "🕹️ Retro & Indie Legends", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "In 'Stardew Valley', which beloved cozy activity allows players to restore their grandfather's land?",
     "options": ["Farming", "Space exploration", "Car racing", "City mayor election"], "correct": "Farming",
     "lore_fact": "Stardew Valley was created entirely by a solo developer named Eric Barone (ConcernedApe)."},
    {"id": "e_indie_8", "category": "indie_retro", "category_label": "🕹️ Retro & Indie Legends", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "What iconic silent protagonist scientist carries a red crowbar in the 'Half-Life' series?",
     "options": ["Gordon Freeman", "Barney Calhoun", "Eli Vance", "Adrian Shephard"], "correct": "Gordon Freeman",
     "lore_fact": "Dr. Gordon Freeman holds a Ph.D. in Theoretical Physics from MIT."},
    {"id": "e_indie_9", "category": "indie_retro", "category_label": "🕹️ Retro & Indie Legends", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "What pioneer 1993 FPS popularized deathmatching and starred Doomguy fighting on Mars?",
     "options": ["DOOM", "Wolfenstein 3D", "Quake", "Duke Nukem 3D"], "correct": "DOOM",
     "lore_fact": "DOOM was created by id Software co-founders John Carmack and John Romero."},
    {"id": "e_indie_10", "category": "indie_retro", "category_label": "🕹️ Retro & Indie Legends", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "In 'Among Us', what title is given to deceptive crewmates sabotaging the spaceship?",
     "options": ["Impostor", "Traitor", "Infiltrator", "Alien"], "correct": "Impostor",
     "lore_fact": "Among Us exploded into global popularity in 2020 two years after its quiet 2018 launch."},

    # Industry Trivia & GOTY (Easy)
    {"id": "e_triv_1", "category": "trivia", "category_label": "🏆 GOTY & Steam Trivia", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "Which game won Game of the Year (GOTY) at The Game Awards 2022?",
     "options": ["Elden Ring", "God of War Ragnarök", "Horizon Forbidden West", "Stray"], "correct": "Elden Ring",
     "lore_fact": "FromSoftware's Elden Ring swept TGA 2022 taking home 4 major awards."},
    {"id": "e_triv_2", "category": "trivia", "category_label": "🏆 GOTY & Steam Trivia", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "Which game won Game of the Year (GOTY) at The Game Awards 2023?",
     "options": ["Baldur's Gate 3", "Alan Wake 2", "The Legend of Zelda: Tears of the Kingdom", "Marvel's Spider-Man 2"], "correct": "Baldur's Gate 3",
     "lore_fact": "Larian Studios' Baldur's Gate 3 won 6 trophies at TGA 2023."},
    {"id": "e_triv_3", "category": "trivia", "category_label": "🏆 GOTY & Steam Trivia", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "What is the primary digital PC storefront and distribution platform operated by Valve?",
     "options": ["Steam", "Epic Games Store", "GOG", "Origin"], "correct": "Steam",
     "lore_fact": "Steam launched on September 12, 2003, originally as an automatic updater for CS 1.6."},
    {"id": "e_triv_4", "category": "trivia", "category_label": "🏆 GOTY & Steam Trivia", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "Who is the co-founder and managing director of Valve Corporation?",
     "options": ["Gabe Newell", "Todd Howard", "Hideo Kojima", "Phil Spencer"], "correct": "Gabe Newell",
     "lore_fact": "Gabe Newell worked at Microsoft for 13 years before co-founding Valve in 1996."},
    {"id": "e_triv_5", "category": "trivia", "category_label": "🏆 GOTY & Steam Trivia", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "What handheld gaming PC hardware device was released by Valve in 2022?",
     "options": ["Steam Deck", "Nintendo Switch", "PlayStation Portal", "ROG Ally"], "correct": "Steam Deck",
     "lore_fact": "The Steam Deck runs SteamOS on Arch Linux using the Proton compatibility layer."},
    {"id": "e_triv_6", "category": "trivia", "category_label": "🏆 GOTY & Steam Trivia", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "What company created the PlayStation family of consoles?",
     "options": ["Sony", "Microsoft", "Nintendo", "Sega"], "correct": "Sony",
     "lore_fact": "The original PlayStation launched in Japan in December 1994."},
    {"id": "e_triv_7", "category": "trivia", "category_label": "🏆 GOTY & Steam Trivia", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "What company created the Xbox gaming console brand?",
     "options": ["Microsoft", "Sony", "Apple", "Intel"], "correct": "Microsoft",
     "lore_fact": "The original Xbox was named after DirectXbox due to its use of DirectX APIs."},
    {"id": "e_triv_8", "category": "trivia", "category_label": "🏆 GOTY & Steam Trivia", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "What game engine created by Epic Games powers Fortnite and hundreds of AAA titles?",
     "options": ["Unreal Engine", "Unity", "CryEngine", "Frostbite"], "correct": "Unreal Engine",
     "lore_fact": "Unreal Engine 5 introduced Nanite micro-polygon geometry and Lumen dynamic lighting."},
    {"id": "e_triv_9", "category": "trivia", "category_label": "🏆 GOTY & Steam Trivia", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "Which game won Game of the Year (GOTY) at The Game Awards 2015?",
     "options": ["The Witcher 3: Wild Hunt", "Fallout 4", "Bloodborne", "Metal Gear Solid V"], "correct": "The Witcher 3: Wild Hunt",
     "lore_fact": "CD Projekt RED's The Witcher 3 took home Game of the Year in 2015."},
    {"id": "e_triv_10", "category": "trivia", "category_label": "🏆 GOTY & Steam Trivia", "difficulty": "rookie", "difficulty_label": "🟢 Rookie", "points": 100,
     "question": "What annual gaming celebration and awards ceremony is hosted every December by Geoff Keighley?",
     "options": ["The Game Awards", "E3", "Gamescom Opening Night", "Tokyo Game Show"], "correct": "The Game Awards",
     "lore_fact": "The Game Awards began in 2014 as the spiritual successor to the Spike Video Game Awards."}
]


MEDIUM_QUESTIONS = [
    # RPG & AAA Lore (Medium)
    {"id": "m_rpg_1", "category": "rpg_lore", "category_label": "🗡️ RPG & AAA Lore", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "In 'Elden Ring', what is the name of General Radahn's miniature scrawny horse?",
     "options": ["Leonard", "Torrent", "Maliketh", "Godefroy"], "correct": "Leonard",
     "lore_fact": "Radahn mastered gravity magic specifically so his immense size wouldn't crush Leonard."},
    {"id": "m_rpg_2", "category": "rpg_lore", "category_label": "🗡️ RPG & AAA Lore", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "In 'Red Dead Redemption 2', what fatal illness does protagonist Arthur Morgan contract?",
     "options": ["Tuberculosis", "Cholera", "Black Plague", "Pneumonia"], "correct": "Tuberculosis",
     "lore_fact": "Arthur contracts TB in Chapter 2 while collecting a debt from Thomas Downes."},
    {"id": "m_rpg_3", "category": "rpg_lore", "category_label": "🗡️ RPG & AAA Lore", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "In 'The Witcher 3', what is Ciri's full royal name and title?",
     "options": ["Cirilla Fiona Elen Riannon", "Cirilla De Rivia", "Yennefer Cirilla Vengerberg", "Cirilla Vattier De Rideaux"], "correct": "Cirilla Fiona Elen Riannon",
     "lore_fact": "Ciri is the Lion Cub of Cintra and bearer of the Elder Blood."},
    {"id": "m_rpg_4", "category": "rpg_lore", "category_label": "🗡️ RPG & AAA Lore", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "In 'Fallout: New Vegas', what casino strip robot rescues you from a shallow grave in Goodsprings?",
     "options": ["Victor", "Yes Man", "ED-E", "FIDO"], "correct": "Victor",
     "lore_fact": "Victor is a Securitron programmed to watch over the Courier on orders from Mr. House."},
    {"id": "m_rpg_5", "category": "rpg_lore", "category_label": "🗡️ RPG & AAA Lore", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "In 'Mass Effect', what ancient synthetic-organic starship race wipes out advanced galactic civilizations every 50,000 years?",
     "options": ["The Reapers", "The Geth", "The Collectors", "The Protheans"], "correct": "The Reapers",
     "lore_fact": "Sovereign, a Reaper vanguard, manipulated Saren Arterius to open the Citadel relay."},
    {"id": "m_rpg_6", "category": "rpg_lore", "category_label": "🗡️ RPG & AAA Lore", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "In 'Cyberpunk 2077', what chip prototype is slotted into V's neural socket?",
     "options": ["Relic 2.0 (biochip)", "Cyberdeck Mk.4", "Sandevistan Warp", "Synapse Accelerant"], "correct": "Relic 2.0 (biochip)",
     "lore_fact": "The Relic was developed by Arasaka to store Johnny Silverhand's digital engram construct."},
    {"id": "m_rpg_7", "category": "rpg_lore", "category_label": "🗡️ RPG & AAA Lore", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "In 'Bloodborne', what is the celestial hunter hub realm where the Plain Doll resides?",
     "options": ["Hunter's Dream", "Yharnam Cathedral", "Byrgenwerth", "The Nightmare Frontier"], "correct": "Hunter's Dream",
     "lore_fact": "The Hunter's Dream was conceived by Gehrman, the First Hunter, under the Moon Presence."},
    {"id": "m_rpg_8", "category": "rpg_lore", "category_label": "🗡️ RPG & AAA Lore", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "In 'Baldur\\'s Gate 3', which companion is a Githyanki fighter seeking the zaith'isk purification device?",
     "options": ["Lae'zel", "Shadowheart", "Karlach", "Minthara"], "correct": "Lae'zel",
     "lore_fact": "Lae'zel is fiercely loyal to Queen Vlaakith before discovering the truth of her ascension."},
    {"id": "m_rpg_9", "category": "rpg_lore", "category_label": "🗡️ RPG & AAA Lore", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "In 'Dark Souls III', who is the final boss at the Kiln of the First Flame that manifests past Lords of Cinder?",
     "options": ["Soul of Cinder", "Nameless King", "Lothric & Lorian", "Gwyn, Lord of Cinder"], "correct": "Soul of Cinder",
     "lore_fact": "In phase 2, the Soul of Cinder adopts Gwyn's moveset and the iconic 'Plin Plin Plon' piano theme."},
    {"id": "m_rpg_10", "category": "rpg_lore", "category_label": "🗡️ RPG & AAA Lore", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "In 'Monster Hunter: World', what is the name of the colossal mountain-sized Elder Dragon that migrates to the New World?",
     "options": ["Zorah Magdaros", "Nergigante", "Xeno'jiiva", "Velkhana"], "correct": "Zorah Magdaros",
     "lore_fact": "The Research Commission redirects Zorah Magdaros into the ocean to prevent the continent's destruction."},

    # PC Hardware & Tech (Medium)
    {"id": "m_hw_1", "category": "hardware", "category_label": "🖥️ PC Hardware & Tech", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "Which dedicated memory on a GPU stores high-res textures, shaders, and frame buffers?",
     "options": ["VRAM (Video RAM)", "L3 CPU Cache", "NVMe Buffer", "DDR5 System RAM"], "correct": "VRAM (Video RAM)",
     "lore_fact": "Modern AAA games at 1440p and 4K ultra settings often require 12GB to 16GB of VRAM."},
    {"id": "m_hw_2", "category": "hardware", "category_label": "🖥️ PC Hardware & Tech", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "What display sync technology eliminates screen tearing by matching monitor refresh rate to GPU output in real-time?",
     "options": ["Variable Refresh Rate (G-Sync / FreeSync)", "Anisotropic Filtering", "Multi-Sample Anti-Aliasing", "Ambient Occlusion"], "correct": "Variable Refresh Rate (G-Sync / FreeSync)",
     "lore_fact": "VRR prevents stuttering and frame tearing without the severe input lag of traditional V-Sync."},
    {"id": "m_hw_3", "category": "hardware", "category_label": "🖥️ PC Hardware & Tech", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "What is AMD's open-source equivalent to NVIDIA DLSS for spatial and temporal upscaling?",
     "options": ["FSR (FidelityFX Super Resolution)", "XeSS", "Radeon Boost", "DirectSR"], "correct": "FSR (FidelityFX Super Resolution)",
     "lore_fact": "AMD FSR runs across all modern GPU architectures including NVIDIA GeForce and Intel Arc."},
    {"id": "m_hw_4", "category": "hardware", "category_label": "🖥️ PC Hardware & Tech", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "Which panel technology is famous for infinite contrast ratios because each individual pixel emits its own light and can turn fully black?",
     "options": ["OLED (Organic Light Emitting Diode)", "IPS (In-Plane Switching)", "TN (Twisted Nematic)", "VA (Vertical Alignment)"], "correct": "OLED (Organic Light Emitting Diode)",
     "lore_fact": "OLED monitors have near-instantaneous 0.03ms pixel response times with true HDR inky blacks."},
    {"id": "m_hw_5", "category": "hardware", "category_label": "🖥️ PC Hardware & Tech", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "What safety mechanism downclocks a CPU or GPU when it reaches dangerous temperatures (e.g. 95°C - 100°C)?",
     "options": ["Thermal Throttling", "Overclocking", "Voltage Spiking", "Bus Saturation"], "correct": "Thermal Throttling",
     "lore_fact": "Thermal throttling lowers core clock frequencies dynamically to prevent permanent silicon heat damage."},
    {"id": "m_hw_6", "category": "hardware", "category_label": "🖥️ PC Hardware & Tech", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "What high-speed expansion bus protocol connects modern graphics cards and NVMe SSDs to the motherboard?",
     "options": ["PCIe (Peripheral Component Interconnect Express)", "SATA III", "USB4", "Thunderbolt"], "correct": "PCIe (Peripheral Component Interconnect Express)",
     "lore_fact": "PCIe 4.0 x16 provides up to 32 GB/s bidirectional bandwidth, while PCIe 5.0 doubles it to 64 GB/s."},
    {"id": "m_hw_7", "category": "hardware", "category_label": "🖥️ PC Hardware & Tech", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "What is the term for the time delay between sending an input on your mouse/keyboard and seeing the reaction on screen?",
     "options": ["Input Latency (System Latency)", "Frame Rate Drop", "Refresh Bandwidth", "Shader Stutter"], "correct": "Input Latency (System Latency)",
     "lore_fact": "NVIDIA Reflex and AMD Anti-Lag reduce the render queue to lower system input latency."},
    {"id": "m_hw_8", "category": "hardware", "category_label": "🖥️ PC Hardware & Tech", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "Which dedicated silicon cores in NVIDIA RTX cards compute ray tracing BVH bounding box intersections?",
     "options": ["RT Cores", "Tensor Cores", "CUDA Cores", "Stream Processors"], "correct": "RT Cores",
     "lore_fact": "RT Cores offload light ray BVH traversal calculations from standard shader execution units."},
    {"id": "m_hw_9", "category": "hardware", "category_label": "🖥️ PC Hardware & Tech", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "What efficiency rating indicates a PC power supply achieves at least 80% to 90%+ energy efficiency under load?",
     "options": ["80 PLUS (Bronze / Gold / Platinum)", "EnergyStar Platinum", "ATX 3.0 Standard", "Watts Master Gold"], "correct": "80 PLUS (Bronze / Gold / Platinum)",
     "lore_fact": "80 PLUS Gold certified power supplies waste under 10% of drawn electricity as excess heat."},
    {"id": "m_hw_10", "category": "hardware", "category_label": "🖥️ PC Hardware & Tech", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "What is the memory standard used in current high-end gaming PC platforms (e.g. AM5, Intel 14th Gen)?",
     "options": ["DDR5 SDRAM", "DDR3 SDRAM", "GDDR6", "HBM2"], "correct": "DDR5 SDRAM",
     "lore_fact": "DDR5 introduces on-die ECC and dual 32-bit subchannels with speeds exceeding 6000 MT/s."},

    # FPS & Esports (Medium)
    {"id": "m_fps_1", "category": "esports", "category_label": "🎯 FPS & Esports", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "In 'VALORANT', which South Korean Duelist agent has an Ultimate called 'Blade Storm' with 5 floating knives?",
     "options": ["Jett", "Reyna", "Raze", "Yoru"], "correct": "Jett",
     "lore_fact": "Jett's Blade Storm knives deal 150 headshot damage and reset all 5 knives upon scoring a kill."},
    {"id": "m_fps_2", "category": "esports", "category_label": "🎯 FPS & Esports", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "In 'Apex Legends', what is the name of the dimension-hopping skirmisher who can create dimensional rift portals?",
     "options": ["Wraith", "Horizon", "Valkyrie", "Ash"], "correct": "Wraith",
     "lore_fact": "Wraith hears voices from the Void that alert her when an enemy sniper is aiming at her."},
    {"id": "m_fps_3", "category": "esports", "category_label": "🎯 FPS & Esports", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "In 'Counter-Strike 2', what is the name of the competitive grenade that temporarily creates an impassable fire zone?",
     "options": ["Molotov (Incendiary Grenade)", "HE Grenade", "Decoy Grenade", "Flashbang"], "correct": "Molotov (Incendiary Grenade)",
     "lore_fact": "In CS2, smoke grenades dynamically extinguish molotov fires upon impact."},
    {"id": "m_fps_4", "category": "esports", "category_label": "🎯 FPS & Esports", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "In 'Overwatch 2', which cybernetic ninja hero has the Ultimate ability 'Dragonblade'?",
     "options": ["Genji", "Hanzo", "Kiriko", "Reaper"], "correct": "Genji",
     "lore_fact": "Genji Shimada was reconstructed into a cyborg body by Dr. Angela Ziegler (Mercy)."},
    {"id": "m_fps_5", "category": "esports", "category_label": "🎯 FPS & Esports", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "In 'Rainbow Six Siege', which British defender places electroclaws that electrify reinforced walls and barbed wire from a distance?",
     "options": ["Kaid", "Bandit", "Mute", "Smoke"], "correct": "Kaid",
     "lore_fact": "Kaid's Rtila Electroclaws can electrify reinforced ceiling hatches from beneath."},
    {"id": "m_fps_6", "category": "esports", "category_label": "🎯 FPS & Esports", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "In 'Counter-Strike', which legendary competitive map features areas called Long A, Catwalk, and B Tunnels?",
     "options": ["Dust II", "Mirage", "Inferno", "Nuke"], "correct": "Dust II",
     "lore_fact": "Dust II was designed by Dave Johnston in 2001 and is the most played map in CS history."},
    {"id": "m_fps_7", "category": "esports", "category_label": "🎯 FPS & Esports", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "In 'VALORANT', which Controller agent from Ghana manipulates cosmic astral form stars across the entire map?",
     "options": ["Astra", "Omen", "Viper", "Harbor"], "correct": "Astra",
     "lore_fact": "Astra enters Astral Form to place stars that can be triggered as smokes, concusses, or gravity wells."},
    {"id": "m_fps_8", "category": "esports", "category_label": "🎯 FPS & Esports", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "In 'Apex Legends', what high-tier armor shield requires dealing 750 evo damage to upgrade to red tier?",
     "options": ["Evo Shield", "Body Shield Lv4", "Gold Armor", "Shield Battery"], "correct": "Evo Shield",
     "lore_fact": "Evo Shields level up dynamically from White to Blue to Purple to Red (125 total HP)."},
    {"id": "m_fps_9", "category": "esports", "category_label": "🎯 FPS & Esports", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "In 'Team Fortress 2', what devastating critical attack state is granted by the Medic's Kritzkrieg medi gun?",
     "options": ["100% Critical Hits (Kritz)", "Invulnerability Shield", "Mega Heal", "Speed Boost"], "correct": "100% Critical Hits (Kritz)",
     "lore_fact": "Unlike the standard ÜberCharge invulnerability, Kritzkrieg grants 8 seconds of pure triple damage."},
    {"id": "m_fps_10", "category": "esports", "category_label": "🎯 FPS & Esports", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "In competitive 'Counter-Strike', what is a round called where a team saves money by only purchasing basic pistols?",
     "options": ["Eco Round (Save Round)", "Force Buy", "Full Buy", "Overtime Buy"], "correct": "Eco Round (Save Round)",
     "lore_fact": "Eco rounds preserve player cash reserves so the team can afford rifles, armor, and utility next round."},

    # Retro & Indie Legends (Medium)
    {"id": "m_indie_1", "category": "indie_retro", "category_label": "🕹️ Retro & Indie Legends", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "In 'Hollow Knight', what ancient underground kingdom was created by the Pale King?",
     "options": ["Hallownest", "Pharloom", "Deepnest", "Dirtmouth"], "correct": "Hallownest",
     "lore_fact": "The Pale King expanded the mind of bugs in Hallownest before the Radiant infection returned."},
    {"id": "m_indie_2", "category": "indie_retro", "category_label": "🕹️ Retro & Indie Legends", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "In 'Hades', what is the name of Zagreus's biological mother, the Queen of the Underworld who fled to Greece?",
     "options": ["Persephone", "Nyx", "Megaera", "Demeter"], "correct": "Persephone",
     "lore_fact": "Zagreus repeatedly attempts to escape the Underworld to find why Persephone left."},
    {"id": "m_indie_3", "category": "indie_retro", "category_label": "🕹️ Retro & Indie Legends", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "In 'Celeste', what mountain is Madeline climbing while confronting her inner anxieties (Badeline)?",
     "options": ["Mount Celeste", "Mount Rainier", "Mount Everest", "Mount Whitney"], "correct": "Mount Celeste",
     "lore_fact": "Celeste's movement mechanics and strawberry collection were praised as masterclass platforming design."},
    {"id": "m_indie_4", "category": "indie_retro", "category_label": "🕹️ Retro & Indie Legends", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "In 'Dead Cells', what headless entity takes control of executed prisoner bodies in the island dungeon?",
     "options": ["The Beheaded (The Homunculus)", "The King", "The Alchemist", "The Collector"], "correct": "The Beheaded (The Homunculus)",
     "lore_fact": "The Homunculus was created by the Alchemist attempting to cure the Malaise plague."},
    {"id": "m_indie_5", "category": "indie_retro", "category_label": "🕹️ Retro & Indie Legends", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "In 'Cuphead', what deal do brothers Cuphead and Mugman make with the Devil at the casino?",
     "options": ["Collect the soul contracts of runaway debtors", "Defeat King Dice in a card duel", "Build a roller coaster", "Surrender their porcelain heads"], "correct": "Collect the soul contracts of runaway debtors",
     "lore_fact": "Studio MDHR hand-drew every animation frame on paper in 1930s rubber-hose style."},
    {"id": "m_indie_6", "category": "indie_retro", "category_label": "🕹️ Retro & Indie Legends", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "In 'Subnautica', what alien ocean planet do players crash-land on after the Aurora spaceship destruction?",
     "options": ["Planet 4546B", "Planet Reach", "Kharak", "Aegis VII"], "correct": "Planet 4546B",
     "lore_fact": "Planet 4546B was quarantined by the Precursor race due to the bacterial Kharaa infection."},
    {"id": "m_indie_7", "category": "indie_retro", "category_label": "🕹️ Retro & Indie Legends", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "In 'Disco Elysium', what is the amnesiac detective protagonist's real name discovered during the investigation?",
     "options": ["Harrier 'Harry' Du Bois", "Kim Kitsuragi", "Titus Hardie", "Evrart Claire"], "correct": "Harrier 'Harry' Du Bois",
     "lore_fact": "Harry is a lieutenant double-yefreitor of the Revachol Citizens Militia (RCM)."},
    {"id": "m_indie_8", "category": "indie_retro", "category_label": "🕹️ Retro & Indie Legends", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "In 'Outer Wilds', how many minutes do you have before the solar system's sun goes supernova and resets the time loop?",
     "options": ["22 Minutes", "15 Minutes", "30 Minutes", "60 Minutes"], "correct": "22 Minutes",
     "lore_fact": "The 22-minute loop was engineered by the ancient Nomai utilizing the Ash Twin Project."},
    {"id": "m_indie_9", "category": "indie_retro", "category_label": "🕹️ Retro & Indie Legends", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "In 'Slay the Spire', which starting character uses metallic armor cards and demonic strength scaling?",
     "options": ["The Ironclad", "The Silent", "The Defect", "The Watcher"], "correct": "The Ironclad",
     "lore_fact": "The Ironclad is the sole surviving warrior of his tribe after selling his soul for demon blood."},
    {"id": "m_indie_10", "category": "indie_retro", "category_label": "🕹️ Retro & Indie Legends", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "In 'Darkest Dungeon', what stress threshold causes a hero to suffer either an Affliction or a heroic Virtue?",
     "options": ["100 Stress", "50 Stress", "200 Stress", "75 Stress"], "correct": "100 Stress",
     "lore_fact": "Reaching 200 stress triggers a fatal heart attack that reduces the hero to Death's Door."},

    # Industry Trivia & GOTY (Medium)
    {"id": "m_triv_1", "category": "trivia", "category_label": "🏆 GOTY & Steam Trivia", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "In 2024, which Chinese action RPG smashed Steam singleplayer concurrent records surpassing 2.4 million players?",
     "options": ["Black Myth: Wukong", "Palworld", "Helldivers 2", "Genshin Impact"], "correct": "Black Myth: Wukong",
     "lore_fact": "Game Science's Black Myth: Wukong peaked at 2,415,714 concurrent players on Steam."},
    {"id": "m_triv_2", "category": "trivia", "category_label": "🏆 GOTY & Steam Trivia", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "Which game won Game of the Year at The Game Awards 2019, beating Death Stranding and Control?",
     "options": ["Sekiro: Shadows Die Twice", "Resident Evil 2 Remake", "Super Smash Bros. Ultimate", "The Outer Worlds"], "correct": "Sekiro: Shadows Die Twice",
     "lore_fact": "FromSoftware director Hidetaka Miyazaki accepted the GOTY trophy for Sekiro."},
    {"id": "m_triv_3", "category": "trivia", "category_label": "🏆 GOTY & Steam Trivia", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "What is the all-time highest concurrent player peak record holder on Steam (3.25 million players in 2018)?",
     "options": ["PUBG: Battlegrounds", "Counter-Strike 2", "Dota 2", "Lost Ark"], "correct": "PUBG: Battlegrounds",
     "lore_fact": "PUBG reached 3,257,248 concurrent Steam players in January 2018."},
    {"id": "m_triv_4", "category": "trivia", "category_label": "🏆 GOTY & Steam Trivia", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "What compatibility layer developed by Valve allows thousands of Windows PC games to run seamlessly on Linux & Steam Deck?",
     "options": ["Proton (Wine-based)", "DirectX Emulation", "Vulkan Wrapper", "DOSBox"], "correct": "Proton (Wine-based)",
     "lore_fact": "Proton integrates DXVK (DirectX to Vulkan translation) developed with open-source contributors."},
    {"id": "m_triv_5", "category": "trivia", "category_label": "🏆 GOTY & Steam Trivia", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "What acclaimed Japanese game auteur created the 'Metal Gear Solid' franchise and 'Death Stranding'?",
     "options": ["Hideo Kojima", "Shinji Mikami", "Hideki Kamiya", "Fumito Ueda"], "correct": "Hideo Kojima",
     "lore_fact": "Hideo Kojima formed independent Kojima Productions in 2015 adopting the Ludens mascot."},
    {"id": "m_triv_6", "category": "trivia", "category_label": "🏆 GOTY & Steam Trivia", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "Which game won Game of the Year at The Game Awards 2021, celebrated for its mandatory 2-player co-op design?",
     "options": ["It Takes Two", "Ratchet & Clank: Rift Apart", "Psychonauts 2", "Metroid Dread"], "correct": "It Takes Two",
     "lore_fact": "Directed by Josef Fares at Hazelight Studios, It Takes Two allows friend passes for free co-op play."},
    {"id": "m_triv_7", "category": "trivia", "category_label": "🏆 GOTY & Steam Trivia", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "What famous 2020 action VR title from Valve returned players to City 17 in the shoes of Eli Vance's daughter?",
     "options": ["Half-Life: Alyx", "Boneworks", "The Lab", "Left 4 Dead VR"], "correct": "Half-Life: Alyx",
     "lore_fact": "Half-Life: Alyx introduced the Physics-driven Gravity Gloves (the 'Russells')."},
    {"id": "m_triv_8", "category": "trivia", "category_label": "🏆 GOTY & Steam Trivia", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "In what year was Valve Corporation officially founded by former Microsoft employees Gabe Newell and Mike Harrington?",
     "options": ["1996", "1998", "2000", "1994"], "correct": "1996",
     "lore_fact": "Valve was founded on August 24, 1996 in Kirkland, Washington."},
    {"id": "m_triv_9", "category": "trivia", "category_label": "🏆 GOTY & Steam Trivia", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "What Polish game development studio created 'The Witcher' trilogy and 'Cyberpunk 2077'?",
     "options": ["CD Projekt RED", "Techland", "People Can Fly", "11 bit studios"], "correct": "CD Projekt RED",
     "lore_fact": "CD Projekt began in the 1990s as a Polish retail distributor importing CD-ROM video games."},
    {"id": "m_triv_10", "category": "trivia", "category_label": "🏆 GOTY & Steam Trivia", "difficulty": "veteran", "difficulty_label": "🟡 Veteran", "points": 200,
     "question": "Which game won Game of the Year at The Game Awards 2018 in a historic duel against Red Dead Redemption 2?",
     "options": ["God of War (2018)", "Marvel's Spider-Man", "Monster Hunter: World", "Celeste"], "correct": "God of War (2018)",
     "lore_fact": "Santa Monica Studio director Cory Barlog directed the seamless single-shot camera masterpiece."}
]


HARD_QUESTIONS = [
    # RPG & AAA Lore (Hard / Elden God)
    {"id": "h_rpg_1", "category": "rpg_lore", "category_label": "🗡️ RPG & AAA Lore", "difficulty": "hardcore", "difficulty_label": "🔴 Hardcore", "points": 350,
     "question": "In 'Dark Souls', what is the exact name of Knight Artorias's Great Grey Wolf guardian?",
     "options": ["Great Grey Wolf Sif", "Vordt of the Boreal Valley", "Alvina of the Darkroot", "Maliketh the Black Blade"], "correct": "Great Grey Wolf Sif",
     "lore_fact": "Sif holds Artorias's Greatsword in its mouth to protect his master's grave from the Abyss."},
    {"id": "h_rpg_2", "category": "rpg_lore", "category_label": "🗡️ RPG & AAA Lore", "difficulty": "god", "difficulty_label": "💀 Elden God", "points": 500,
     "question": "In 'Elden Ring', what is the hidden true identity of Queen Marika the Eternal's male counterpart and second husband?",
     "options": ["Radagon of the Golden Order", "Godfrey, First Elden Lord", "Maliketh the Beast Clergyman", "Miquella the Unalloyed"], "correct": "Radagon of the Golden Order",
     "lore_fact": "The secret sculpture in Leyndell proclaims: 'Radagon is Marika'."},
    {"id": "h_rpg_3", "category": "rpg_lore", "category_label": "🗡️ RPG & AAA Lore", "difficulty": "hardcore", "difficulty_label": "🔴 Hardcore", "points": 350,
     "question": "In 'Cyberpunk 2077', which legendary rock band fronted by Johnny Silverhand recorded 'Chippin\\' In'?",
     "options": ["SAMURAI", "Chrome Rockers", "Night City Maelstrom", "Tyger Claws"], "correct": "SAMURAI",
     "lore_fact": "In the real world, Swedish punk band Refused wrote and recorded SAMURAI's soundtrack."},
    {"id": "h_rpg_4", "category": "rpg_lore", "category_label": "🗡️ RPG & AAA Lore", "difficulty": "hardcore", "difficulty_label": "🔴 Hardcore", "points": 350,
     "question": "In 'Baldur\\'s Gate 3', what netherese artifact crowns the Absolute Netherbrain to grant it godhood?",
     "options": ["Crown of Karsus", "Eye of Vecna", "Orb of Netheril", "Ring of Winter"], "correct": "Crown of Karsus",
     "lore_fact": "The Crown of Karsus was forged by ancient archwizard Karsus before the fall of Netheril."},
    {"id": "h_rpg_5", "category": "rpg_lore", "category_label": "🗡️ RPG & AAA Lore", "difficulty": "god", "difficulty_label": "💀 Elden God", "points": 500,
     "question": "In 'Bloodborne', what is the true final Great One cosmic entity fought if you consume three Third of Umbilical Cords?",
     "options": ["Moon Presence (Flora)", "Ebrietas, Daughter of the Cosmos", "Mergo's Wet Nurse", "Oedon the Formless"], "correct": "Moon Presence (Flora)",
     "lore_fact": "Defeating the Moon Presence ascends the Hunter into an infant Great One to shepherd humanity."},
    {"id": "h_rpg_6", "category": "rpg_lore", "category_label": "🗡️ RPG & AAA Lore", "difficulty": "hardcore", "difficulty_label": "🔴 Hardcore", "points": 350,
     "question": "In 'The Witcher 3: Blood and Wine', what is the name of the ancient higher vampire elder who slumbers in the Unseen Elder's cave?",
     "options": ["The Unseen Elder", "Dettlaff van der Eretein", "Emiel Regis Rohellec Terzieff-Godefroy", "Hubert Rejk"], "correct": "The Unseen Elder",
     "lore_fact": "The Unseen Elder guards the gateway connecting the Witcher world to the vampire home realm."},
    {"id": "h_rpg_7", "category": "rpg_lore", "category_label": "🗡️ RPG & AAA Lore", "difficulty": "hardcore", "difficulty_label": "🔴 Hardcore", "points": 350,
     "question": "In 'Fallout 3', what is the name of the colossal anti-communist brotherhood robot built under the Pentagon?",
     "options": ["Liberty Prime", "Optimus Prime", "Securitron Prime", "Iron Brotherhood"], "correct": "Liberty Prime",
     "lore_fact": "Liberty Prime was built for the liberation of Anchorage, Alaska, throwing nuclear football bombs."},
    {"id": "h_rpg_8", "category": "rpg_lore", "category_label": "🗡️ RPG & AAA Lore", "difficulty": "god", "difficulty_label": "💀 Elden God", "points": 500,
     "question": "In 'Demon\\'s Souls', what is the soul level draining spell cast by King Allant that permanently steals your character levels?",
     "options": ["Soul Siphon (Soulsucker)", "Firestorm", "God's Wrath", "Acid Cloud"], "correct": "Soul Siphon (Soulsucker)",
     "lore_fact": "Old King Allant's grab attack drains exactly 1 soul level from your highest stat permanently."},
    {"id": "h_rpg_9", "category": "rpg_lore", "category_label": "🗡️ RPG & AAA Lore", "difficulty": "hardcore", "difficulty_label": "🔴 Hardcore", "points": 350,
     "question": "In 'Mass Effect 2', what is the technical name of the human Reaper embryo larva being constructed inside the Collector Base?",
     "options": ["Human-Reaper Larva", "Leviathan Construct", "Harbinger Prototype", "Sovereign Core"], "correct": "Human-Reaper Larva",
     "lore_fact": "The Collectors were liquefying millions of kidnapped human colonists to build the Reaper core."},
    {"id": "h_rpg_10", "category": "rpg_lore", "category_label": "🗡️ RPG & AAA Lore", "difficulty": "god", "difficulty_label": "💀 Elden God", "points": 500,
     "question": "In 'The Elder Scrolls III: Morrowind', which Dwemer Tonal Architect crafted Keening and Sunder to harvest the Heart of Lorkhan?",
     "options": ["Lord Kagrenac", "Yagrum Bagarn", "Dumac Dwarfking", "Sotha Sil"], "correct": "Lord Kagrenac",
     "lore_fact": "Striking the Heart of Lorkhan with Kagrenac's Tools caused the entire Dwemer race to vanish instantly."},

    # PC Hardware & Tech (Hard / Elden God)
    {"id": "h_hw_1", "category": "hardware", "category_label": "🖥️ PC Hardware & Tech", "difficulty": "hardcore", "difficulty_label": "🔴 Hardcore", "points": 350,
     "question": "When a GPU operates at low % utilization because the CPU cannot dispatch draw calls quickly enough, what is this phenomenon called?",
     "options": ["CPU Bottleneck", "Thermal Throttling", "PCIe Saturation", "Shader Cache Stutter"], "correct": "CPU Bottleneck",
     "lore_fact": "In CPU bottlenecks, lowering rendering resolution from 4K to 1080p yields zero FPS improvement."},
    {"id": "h_hw_2", "category": "hardware", "category_label": "🖥️ PC Hardware & Tech", "difficulty": "god", "difficulty_label": "💀 Elden God", "points": 500,
     "question": "Which AMD 3D V-Cache processor set global gaming performance benchmarks by stacking a 64MB SRAM die directly over its compute core?",
     "options": ["Ryzen 7 7800X3D", "Ryzen 9 7900X", "Ryzen 5 7600X", "Threadripper 7980X"], "correct": "Ryzen 7 7800X3D",
     "lore_fact": "Direct TSV (Through-Silicon Vias) bonding provides 2.5 TB/s bandwidth between the cache and CPU cores."},
    {"id": "h_hw_3", "category": "hardware", "category_label": "🖥️ PC Hardware & Tech", "difficulty": "hardcore", "difficulty_label": "🔴 Hardcore", "points": 350,
     "question": "What hardware ray tracing data structure organizes 3D geometry into hierarchical bounding boxes for efficient ray intersection queries?",
     "options": ["BVH (Bounding Volume Hierarchy)", "KD-Tree Grid", "Octree Splatting", "Voxel Grid Array"], "correct": "BVH (Bounding Volume Hierarchy)",
     "lore_fact": "RT cores traverse the BVH tree in hardware, skipping millions of triangles that the ray will never touch."},
    {"id": "h_hw_4", "category": "hardware", "category_label": "🖥️ PC Hardware & Tech", "difficulty": "hardcore", "difficulty_label": "🔴 Hardcore", "points": 350,
     "question": "What is the phenomenon called when shader pipelines compile in real-time during gameplay, causing instantaneous frame drops?",
     "options": ["Shader Compilation Stutter", "Texture Pop-in", "Tearing Artifact", "Bus Thrashing"], "correct": "Shader Compilation Stutter",
     "lore_fact": "Modern PC ports pre-compile Pipeline State Objects (PSOs) during the game's initial startup to prevent stutters."},
    {"id": "h_hw_5", "category": "hardware", "category_label": "🖥️ PC Hardware & Tech", "difficulty": "god", "difficulty_label": "💀 Elden God", "points": 500,
     "question": "What high-speed low-level API feature allows the CPU to map the GPU's entire VRAM address space into system memory across PCIe?",
     "options": ["Resizable BAR (Smart Access Memory)", "DirectStorage 1.2", "DirectX Raytracing 1.1", "Vulkan Bindless"], "correct": "Resizable BAR (Smart Access Memory)",
     "lore_fact": "Traditionally CPUs were limited to small 256MB VRAM apertures; Resizable BAR removes that bottleneck."},
    {"id": "h_hw_6", "category": "hardware", "category_label": "🖥️ PC Hardware & Tech", "difficulty": "hardcore", "difficulty_label": "🔴 Hardcore", "points": 350,
     "question": "What power delivery component on motherboards converts 12V PSU input into fine-tuned sub-1.3V core voltage for the CPU?",
     "options": ["VRM (Voltage Regulator Module)", "PCH Chipset", "Super I/O Controller", "CMOS Battery"], "correct": "VRM (Voltage Regulator Module)",
     "lore_fact": "Multi-phase VRMs use high-amperage MOSFETs and chokes to supply clean current without overheating."},
    {"id": "h_hw_7", "category": "hardware", "category_label": "🖥️ PC Hardware & Tech", "difficulty": "god", "difficulty_label": "💀 Elden God", "points": 500,
     "question": "In monitor pixel response times, what measurement tracks how fast a pixel transitions from one shade of gray to another?",
     "options": ["GtG (Gray to Gray)", "MPRT (Moving Picture Response Time)", "PWM Cycle", "Flicker Hz"], "correct": "GtG (Gray to Gray)",
     "lore_fact": "True sub-1ms GtG prevents ghosting and smearing trails during high-speed camera pans."},
    {"id": "h_hw_8", "category": "hardware", "category_label": "🖥️ PC Hardware & Tech", "difficulty": "hardcore", "difficulty_label": "🔴 Hardcore", "points": 350,
     "question": "What Microsoft technology allows games on NVMe SSDs to bypass the CPU and decompress assets directly on the GPU?",
     "options": ["DirectStorage", "AutoHDR", "Xbox Game Bar", "DirectML"], "correct": "DirectStorage",
     "lore_fact": "GPU decompression (GDeflate) frees up multiple CPU cores and delivers near-instantaneous load screens."},
    {"id": "h_hw_9", "category": "hardware", "category_label": "🖥️ PC Hardware & Tech", "difficulty": "hardcore", "difficulty_label": "🔴 Hardcore", "points": 350,
     "question": "What high-density graphics memory type stacks memory dies in 3D vertically right beside the GPU die using an interposer?",
     "options": ["HBM (High Bandwidth Memory)", "GDDR6X", "LPDDR5X", "DDR5"], "correct": "HBM (High Bandwidth Memory)",
     "lore_fact": "HBM uses ultra-wide 1024-bit memory buses achieving multiple terabytes per second bandwidth."},
    {"id": "h_hw_10", "category": "hardware", "category_label": "🖥️ PC Hardware & Tech", "difficulty": "god", "difficulty_label": "💀 Elden God", "points": 500,
     "question": "What is the name of the new high-power 16-pin 12V-2x6 / 12VHPWR PCIe power connector standard introduced with ATX 3.0?",
     "options": ["12VHPWR (12V-2x6)", "EPS 12V 8-Pin", "Molex 4-Pin", "PCIe Gen4 Dual-8Pin"], "correct": "12VHPWR (12V-2x6)",
     "lore_fact": "12VHPWR supplies up to 600 Watts through a single compact cable using 4 sideband sense pins."},

    # FPS & Esports (Hard / Elden God)
    {"id": "h_fps_1", "category": "esports", "category_label": "🎯 FPS & Esports", "difficulty": "hardcore", "difficulty_label": "🔴 Hardcore", "points": 350,
     "question": "In 'Counter-Strike', what is the exact base damage of a point-blank Desert Eagle headshot through a Kevlar helmet?",
     "options": ["140+ damage (Instant Kill)", "95 damage", "85 damage", "75 damage"], "correct": "140+ damage (Instant Kill)",
     "lore_fact": "The Desert Eagle is the only standard pistol capable of one-shot killing helmeted targets across long ranges."},
    {"id": "h_fps_2", "category": "esports", "category_label": "🎯 FPS & Esports", "difficulty": "god", "difficulty_label": "💀 Elden God", "points": 500,
     "question": "In 'Counter-Strike: Global Offensive', which professional player pulled off the historic jumping double AWP noscope on Mirage B Apartments (Major 2016)?",
     "options": ["coldzera (Marcelo David)", "s1mple (Oleksandr Kostyliev)", "device (Nicolai Reedtz)", "FalleN (Gabriel Toledo)"], "correct": "coldzera (Marcelo David)",
     "lore_fact": "Valve commemorated coldzera's miracle play by painting a winged AWP graffiti with 4 skull bullets on Mirage B van."},
    {"id": "h_fps_3", "category": "esports", "category_label": "🎯 FPS & Esports", "difficulty": "hardcore", "difficulty_label": "🔴 Hardcore", "points": 350,
     "question": "In 'VALORANT', which Initiator agent from Australia carries a Recon Dart and Owl Drone?",
     "options": ["Sova", "Breach", "Skye", "Fade"], "correct": "Sova",
     "lore_fact": "Sova uses his mechanical hunter bow to calculate double bounce recon arrows across entire map skyboxes."},
    {"id": "h_fps_4", "category": "esports", "category_label": "🎯 FPS & Esports", "difficulty": "hardcore", "difficulty_label": "🔴 Hardcore", "points": 350,
     "question": "In 'Apex Legends', which defensive legend deploys the Interception Pylon that zaps incoming artillery shells and grenades?",
     "options": ["Wattson (Natalie Paquette)", "Caustic", "Catalyst", "Rampart"], "correct": "Wattson (Natalie Paquette)",
     "lore_fact": "Wattson is the daughter of the Apex Games' lead electrical engineer who designed the Ring itself."},
    {"id": "h_fps_5", "category": "esports", "category_label": "🎯 FPS & Esports", "difficulty": "god", "difficulty_label": "💀 Elden God", "points": 500,
     "question": "In 'Counter-Strike' Major history, which Danish roster became the first team to win 4 CS:GO Majors, including 3 consecutive titles (2018-2019)?",
     "options": ["Astralis", "Fnatic", "Natus Vincere", "Ninjas in Pyjamas"], "correct": "Astralis",
     "lore_fact": "Astralis (gla1ve, device, dupreeh, Magisk, Xyp9x, coach zonic) revolutionized utility usage and crossfire setups."},
    {"id": "h_fps_6", "category": "esports", "category_label": "🎯 FPS & Esports", "difficulty": "hardcore", "difficulty_label": "🔴 Hardcore", "points": 350,
     "question": "In 'Quake III Arena' and Source engine physics, what movement technique involves timed diagonal jumping to build uncapped velocity?",
     "options": ["Strafe Jumping / Bunny Hopping", "Rocket Jumping", "Wall Running", "Super Sliding"], "correct": "Strafe Jumping / Bunny Hopping",
     "lore_fact": "Strafe jumping exploits vector math where turning the view angle during acceleration exceeds standard speed caps."},
    {"id": "h_fps_7", "category": "esports", "category_label": "🎯 FPS & Esports", "difficulty": "hardcore", "difficulty_label": "🔴 Hardcore", "points": 350,
     "question": "In 'Rainbow Six Siege', what is the name of the French GIGN defender whose armor plates boost team down-but-not-out survivability?",
     "options": ["Rook (Julien Nizan)", "Doc", "Montagne", "Twitch"], "correct": "Rook (Julien Nizan)",
     "lore_fact": "Rook's R1N 'Rhino' Armor plates guarantee that any player not headshot enters a DBNO state instead of instant death."},
    {"id": "h_fps_8", "category": "esports", "category_label": "🎯 FPS & Esports", "difficulty": "god", "difficulty_label": "💀 Elden God", "points": 500,
     "question": "In 'Team Fortress 2' competitive 6v6 meta, what is the standard optimal team class composition?",
     "options": ["2 Scouts, 2 Soldiers, 1 Demoman, 1 Medic", "2 Heavies, 2 Snipers, 1 Spy, 1 Medic", "1 of each class", "3 Scouts, 2 Soldiers, 1 Medic"], "correct": "2 Scouts, 2 Soldiers, 1 Demoman, 1 Medic",
     "lore_fact": "This 6v6 'cookie-cutter' meta offers the perfect balance of aerial mobility, area denial, and burst heal."},
    {"id": "h_fps_9", "category": "esports", "category_label": "🎯 FPS & Esports", "difficulty": "hardcore", "difficulty_label": "🔴 Hardcore", "points": 350,
     "question": "In 'VALORANT', how many seconds does the Spike take to detonate once planted?",
     "options": ["45 Seconds", "35 Seconds", "40 Seconds", "50 Seconds"], "correct": "45 Seconds",
     "lore_fact": "Defusing the Spike takes exactly 7 seconds total (with a 3.5s half-defuse checkpoint)."},
    {"id": "h_fps_10", "category": "esports", "category_label": "🎯 FPS & Esports", "difficulty": "god", "difficulty_label": "💀 Elden God", "points": 500,
     "question": "In 'Counter-Strike 2', what groundbreaking server architecture replaced traditional 64-tick and 128-tick rate systems?",
     "options": ["Sub-Tick Architecture", "Dynamic 256-Tick", "Client-Side Rollback", "Deterministic Netcode"], "correct": "Sub-Tick Architecture",
     "lore_fact": "Sub-tick records precise timestamps for button clicks between server ticks so shooting and jumping register instantly."},

    # Retro & Indie Legends (Hard / Elden God)
    {"id": "h_indie_1", "category": "indie_retro", "category_label": "🕹️ Retro & Indie Legends", "difficulty": "hardcore", "difficulty_label": "🔴 Hardcore", "points": 350,
     "question": "In 'DOOM' (1993), what legendary cheat code grants full invulnerability god mode?",
     "options": ["IDDQD", "IDKFA", "IDCLIP", "NOCLIP"], "correct": "IDDQD",
     "lore_fact": "IDDQD turned Doomguy's eyes gold and made him completely immune to monster damage."},
    {"id": "h_indie_2", "category": "indie_retro", "category_label": "🕹️ Retro & Indie Legends", "difficulty": "god", "difficulty_label": "💀 Elden God", "points": 500,
     "question": "In 'Half-Life 2', what is the official scientific model name of the Zero Point Energy Field Manipulator?",
     "options": ["Gravity Gun", "Tau Cannon", "Gluon Gun", "Portal Gun"], "correct": "Gravity Gun",
     "lore_fact": "The Gravity Gun becomes supercharged with dark energy inside the Combine Citadel, picking up organic matter."},
    {"id": "h_indie_3", "category": "indie_retro", "category_label": "🕹️ Retro & Indie Legends", "difficulty": "hardcore", "difficulty_label": "🔴 Hardcore", "points": 350,
     "question": "In 'Hollow Knight', what is the ultimate endgame boss at the pinnacle of the Pantheon of Hallownest in Godhome?",
     "options": ["Absolute Radiance", "Pure Vessel", "Nightmare King Grimm", "The Hollow Knight"], "correct": "Absolute Radiance",
     "lore_fact": "Defeating Absolute Radiance at the top of the 50-boss Pantheon unlocks the 'Embrace the Void' ending."},
    {"id": "h_indie_4", "category": "indie_retro", "category_label": "🕹️ Retro & Indie Legends", "difficulty": "god", "difficulty_label": "💀 Elden God", "points": 500,
     "question": "In 'DOOM II', what is the final boss of Map30 where John Romero's severed head on a stick is hidden behind a wall?",
     "options": ["Icon of Sin (Baphomet)", "Cyberdemon", "Spider Mastermind", "Arch-Vile"], "correct": "Icon of Sin (Baphomet)",
     "lore_fact": "Shooting rockets into the demon brain hits John Romero's hidden head sprite, which plays a reversed audio Easter egg."},
    {"id": "h_indie_5", "category": "indie_retro", "category_label": "🕹️ Retro & Indie Legends", "difficulty": "hardcore", "difficulty_label": "🔴 Hardcore", "points": 350,
     "question": "In 'Ultima Online' (1997), what notorious player assassinated the allegedly invincible developer avatar Lord British (Richard Garriott)?",
     "options": ["Rainz", "Kerrid", "Drizzt", "Shadowcrafter"], "correct": "Rainz",
     "lore_fact": "Rainz cast a Fire Field spell during a server stress test when Lord British forgot to toggle his god mode invulnerability."},
    {"id": "h_indie_6", "category": "indie_retro", "category_label": "🕹️ Retro & Indie Legends", "difficulty": "hardcore", "difficulty_label": "🔴 Hardcore", "points": 350,
     "question": "In 'Deus Ex' (2000), what is the name of the secret military nano-augmented protagonist working for UNATCO?",
     "options": ["JC Denton", "Paul Denton", "Adam Jensen", "Gunther Hermann"], "correct": "JC Denton",
     "lore_fact": "JC stands for 'Jesus Christ' Denton, designed by Ion Storm director Warren Spector."},
    {"id": "h_indie_7", "category": "indie_retro", "category_label": "🕹️ Retro & Indie Legends", "difficulty": "god", "difficulty_label": "💀 Elden God", "points": 500,
     "question": "In 'System Shock 2', what iconic line is uttered when rogue AI SHODAN reveals she has been masquerading as Dr. Janice Polito?",
     "options": ["'Look at you, hacker: a pathetic creature of meat and bone...'", "'The cake is a lie'", "'Would you kindly...'", "'War never changes'"], "correct": "'Look at you, hacker: a pathetic creature of meat and bone...'",
     "lore_fact": "SHODAN was voiced by Terri Brosius and inspired countless AI villains including GLaDOS."},
    {"id": "h_indie_8", "category": "indie_retro", "category_label": "🕹️ Retro & Indie Legends", "difficulty": "hardcore", "difficulty_label": "🔴 Hardcore", "points": 350,
     "question": "In 'FTL: Faster Than Light', what rebel flagship weapon room is traditionally disabled first by teleporter boarding parties?",
     "options": ["Triple Missile Launcher", "Ion Cannon", "Laser Battery", "Beam Weapon"], "correct": "Triple Missile Launcher",
     "lore_fact": "The isolated weapon artillery rooms in FTL on Easy/Normal have no doors connecting to the main hull crew."},
    {"id": "h_indie_9", "category": "indie_retro", "category_label": "🕹️ Retro & Indie Legends", "difficulty": "god", "difficulty_label": "💀 Elden God", "points": 500,
     "question": "In 'Castlevania: Symphony of the Night', what item must Alucard wear during the fight against Richter Belmont to reveal Shaft?",
     "options": ["Holy Glasses", "Gold Ring", "Silver Ring", "Jewel of Open"], "correct": "Holy Glasses",
     "lore_fact": "Wearing the Holy Glasses allows you to attack the green mind control orb floating above Richter, unlocking the Inverted Castle."},
    {"id": "h_indie_10", "category": "indie_retro", "category_label": "🕹️ Retro & Indie Legends", "difficulty": "hardcore", "difficulty_label": "🔴 Hardcore", "points": 350,
     "question": "In 'The Binding of Isaac', what is the name of the secret final void area unlocked by defeating Hush?",
     "options": ["The Void (Delirium)", "The Dark Room", "The Chest", "Sheol"], "correct": "The Void (Delirium)",
     "lore_fact": "Delirium teleports and rapidly morphs into every boss Isaac encountered during the run."},

    # Industry Trivia & GOTY (Hard / Elden God)
    {"id": "h_triv_1", "category": "trivia", "category_label": "🏆 GOTY & Steam Trivia", "difficulty": "god", "difficulty_label": "💀 Elden God", "points": 500,
     "question": "What was the very first game distributed on Steam when Valve launched the platform on September 12, 2003?",
     "options": ["Counter-Strike 1.6", "Half-Life 2", "Team Fortress Classic", "Day of Defeat"], "correct": "Counter-Strike 1.6",
     "lore_fact": "Steam was required to play CS 1.6 in September 2003, more than a year before Half-Life 2 launched in Nov 2004."},
    {"id": "h_triv_2", "category": "trivia", "category_label": "🏆 GOTY & Steam Trivia", "difficulty": "hardcore", "difficulty_label": "🔴 Hardcore", "points": 350,
     "question": "Which game won the inaugural Game of the Year at the very first The Game Awards in 2014?",
     "options": ["Dragon Age: Inquisition", "Middle-earth: Shadow of Mordor", "Dark Souls II", "Bayonetta 2"], "correct": "Dragon Age: Inquisition",
     "lore_fact": "BioWare's Dragon Age: Inquisition took the very first TGA GOTY trophy in December 2014."},
    {"id": "h_triv_3", "category": "trivia", "category_label": "🏆 GOTY & Steam Trivia", "difficulty": "hardcore", "difficulty_label": "🔴 Hardcore", "points": 350,
     "question": "In 2007, what Valve puzzle masterpiece was included as a surprise bonus game inside 'The Orange Box' bundle?",
     "options": ["Portal", "Peggle Extreme", "Team Fortress 2", "Half-Life 2: Episode Two"], "correct": "Portal",
     "lore_fact": "Portal originated as a student project called 'Narbacular Drop' from DigiPen before Valve hired the entire team."},
    {"id": "h_triv_4", "category": "trivia", "category_label": "🏆 GOTY & Steam Trivia", "difficulty": "god", "difficulty_label": "💀 Elden God", "points": 500,
     "question": "What was the codename of the canceled 2003 Half-Life 2 source code leak that forced Valve to delay the game?",
     "options": ["Anon / Gemba Leak (Axel Gembe)", "Project City 17", "Source 2003 Alpha", "Black Mesa Leak"], "correct": "Anon / Gemba Leak (Axel Gembe)",
     "lore_fact": "German hacker Axel Gembe breached Valve's internal network via an unpatched Outlook vulnerability in late 2003."},
    {"id": "h_triv_5", "category": "trivia", "category_label": "🏆 GOTY & Steam Trivia", "difficulty": "hardcore", "difficulty_label": "🔴 Hardcore", "points": 350,
     "question": "Which game won Game of the Year at The Game Awards 2016, beating Uncharted 4 and DOOM?",
     "options": ["Overwatch", "Inside", "Titanfall 2", "Dark Souls III"], "correct": "Overwatch",
     "lore_fact": "Blizzard Entertainment's Overwatch was directed by Jeff Kaplan and won GOTY in 2016."},
    {"id": "h_triv_6", "category": "trivia", "category_label": "🏆 GOTY & Steam Trivia", "difficulty": "god", "difficulty_label": "💀 Elden God", "points": 500,
     "question": "In 1999, which duo originally created 'Counter-Strike' as a free Half-Life mod before Valve acquired the rights?",
     "options": ["Minh Le (Gooseman) & Jess Cliffe (Cliffe)", "John Carmack & John Romero", "Robin Walker & John Cook", "Gabe Newell & Marc Laidlaw"], "correct": "Minh Le (Gooseman) & Jess Cliffe (Cliffe)",
     "lore_fact": "Minh Le created the 3D models while Jess Cliffe voiced the iconic radio lines ('Bomb has been planted')."},
    {"id": "h_triv_7", "category": "trivia", "category_label": "🏆 GOTY & Steam Trivia", "difficulty": "hardcore", "difficulty_label": "🔴 Hardcore", "points": 350,
     "question": "Which game won Game of the Year at The Game Awards 2017?",
     "options": ["The Legend of Zelda: Breath of the Wild", "Super Mario Odyssey", "Persona 5", "Horizon Zero Dawn"], "correct": "The Legend of Zelda: Breath of the Wild",
     "lore_fact": "Nintendo director Hidemaro Fujibayashi and producer Eiji Aonuma accepted the GOTY trophy."},
    {"id": "h_triv_8", "category": "trivia", "category_label": "🏆 GOTY & Steam Trivia", "difficulty": "god", "difficulty_label": "💀 Elden God", "points": 500,
     "question": "What 1998 Valve shooter pioneered narrative storytelling without cutscenes, using scripted in-game sequences?",
     "options": ["Half-Life", "Quake II", "Unreal", "SiN"], "correct": "Half-Life",
     "lore_fact": "Half-Life won over 50 Game of the Year awards in 1998 running on the GoldSrc engine (modified Quake engine)."},
    {"id": "h_triv_9", "category": "trivia", "category_label": "🏆 GOTY & Steam Trivia", "difficulty": "hardcore", "difficulty_label": "🔴 Hardcore", "points": 350,
     "question": "In 2024, what Swedish studio developed the mega-hit co-op shooter 'Helldivers 2' published by Sony on PC and PS5?",
     "options": ["Arrowhead Game Studios", "DICE", "Fatshark", "MachineGames"], "correct": "Arrowhead Game Studios",
     "lore_fact": "Arrowhead CEO Johan Pilestedt and team used the discontinued Autodesk Stingray engine for Helldivers 2."},
    {"id": "h_triv_10", "category": "trivia", "category_label": "🏆 GOTY & Steam Trivia", "difficulty": "god", "difficulty_label": "💀 Elden God", "points": 500,
     "question": "What was the very first video game commercial ever broadcast on television in 1972?",
     "options": ["Magnavox Odyssey", "Atari Pong", "Space Invaders", "Computer Space"], "correct": "Magnavox Odyssey",
     "lore_fact": "The 1972 commercial featured Frank Sinatra's music and showed families playing on the world's first home console."}
]

QUIZ_QUESTION_BANK = EASY_QUESTIONS + MEDIUM_QUESTIONS + HARD_QUESTIONS
